export const GET_DISPLAY_DATA = 'GET_DISPLAY_DATA';
export const SAVE_UPDATE_DATA = 'SAVE_UPDATE_DATA';
export const RELOADE_FILE_DATA = 'RELOADE_FILE_DATA';
export const INPUT_FIELD_ERROR = 'INPUT_FIELD_ERROR';
export const HIDE_MENU_ITEM = 'HIDE_MENU_ITEM'
export const SHOW_MENU_ITEM = 'SHOW_MENU_ITEM'
export const SAVE_ALPHA_DATA = 'SAVE_ALPHA_DATA'
